[project]
name = "shorter"
version = "1.0.0"
description = "Version 1 of a Url shortener application"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "mongomock-motor>=0.0.36",
    "motor>=3.7.1",
    "pydantic-settings>=2.10.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-tornasync>=0.6.0.post2",
    "pytest-trio>=0.8.0",
    "pytest-twisted>=1.14.3",
    "twisted>=25.5.0",
    "uvicorn>=0.35.0",
]